### ISSUE TITLE
Suggestion: separate badword log from mods log

### ISSUE THREAD

**Issue by paolojpa** [aternosorg/modbot#354]
It could be cool if the badword logs sent in another channel. For not mixing it with the mod actions like mute, bans, etc.

**Comment by FlitzDev** [comment]
I agree, but maybe not splitting it into another log option. Just with the message logs themself imo^

**Comment by paolojpa** [comment]
I think its better in another channel. It doesn't look very well mixing mods things with the deleted words.
![Screenshot_1](https://user-images.githubusercontent.com/73677465/130510392-bf6dac4f-a34a-47ea-99b8-fc5a46329156.png)

**Comment by ScourgeTheHedgehog** [comment]
To get back to this myself

Automod is a great feature, but it's a real big interference when having public modlogs (transparency). It defeats the purpose of automod because the same thing that automod deleted would just reappear in the public modlogs channel. 

I will elaborate on my personal suggestion in a better manner:

Fully agree with @paolojpa, it should be seperated from the modlogs themself. Perhaps as another seperate option, but imho it should be included with the normal message logs instead.

![image](https://user-images.githubusercontent.com/34064010/131261439-29a537b5-4849-4d69-90f8-47febd0b1645.png)
